### ISSUE TITLE
No module named 'aster'

### ISSUE THREAD

**Issue by zhaoyangze** [bgshih/aster#10]
/home/zhaoyangze/anaconda3/envs/tf/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "aster/demo.py", line 8, in <module>
    from aster.protos import pipeline_pb2
ModuleNotFoundError: No module named 'aster'
This happens when I execute python3 demo.py.Anyone can help？

**Comment by zhaoyangze** [comment]
I have added the path.

**Comment by zhaoyangze** [comment]
solved

**Comment by xiaoaoran** [comment]
how?

**Comment by JingLiJJ** [comment]
> solved

Hello~ Can you please tell me how to add a path to solve?

**Comment by pageedward** [comment]
@zhaoyangze do u use a anaconda env to run it ? if so ,how to add PYTHON PATH?

**Comment by TemiLee** [comment]
I have the same problem , can you tell me how to solve it ?

**Comment by TemiLee** [comment]
@zhaoyangze @JingLiJJ @pageedward

**Comment by 20180821** [comment]
> 我添加了路径。

请问怎么添加路径，希望得到你的回复

**Comment by 20180821** [comment]
> 我有同样的问题，你能告诉我如何解决它吗？

请问这个问题你现在解决了吗

**Comment by 20180821** [comment]
> > 解决了
> 
> 您好〜能告诉我如何添加解决路径吗？

请问这个问题你现在解决了吗

**Comment by JingLiJJ** [comment]
Sorry I didn’t solve it.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by 20180821** [comment]
题主，请问怎么解决这个问题啊，分享一下啊

**Comment by 13muskanp** [comment]
For solving that issue, just remove aster from:
from aster.protos import pipeline_pb2
from aster.builders import model_builder
while importing. It should look like this:
from protos import pipeline_pb2
from builders import model_builder

This will definitely solve the issue.

**Comment by DanLiu0623** [comment]
添加路径的时候，作者说的Add `/path/to/aster` to `PYTHONPATH`, or set this variable for every run会报ModuleNotFoundError: No module named 'aster'这个错误。添加到aster的上一层路径就可以了，比如我的目录是/data0/aster。我在添加的时候就是export PYTHONPATH=/data0，就可以了。
