### ISSUE TITLE
How about python2?

### ISSUE THREAD

**Issue by lipond** [bgshih/aster#23]
Hi,

Much appreciate this project and thanks.

One of my issues is about the compatibility with python2, did you do some tests for python2?

Br.

**Comment by lipond** [comment]
I have tested the codes by using Python2.7 and it runs well.

**Comment by Cabbagehust2507** [comment]
> I have tested the codes using Python2.7 and it runs well.

Can you tell me how you run with python2.7? What parameters or settings need to be changed?
Thank you.
