### ISSUE TITLE
Confidence score for each recognized word

### ISSUE THREAD

**Issue by nikita0511** [bgshih/aster#31]
Hi,

How do we map prediction score (which is a negative value in most cases) to a confidence value between 0 and 1. I need to check by what probability each word was recognized by the model.

Thanks.

**Comment by dsandii** [comment]
@nikita0511 Did you find a solution to this? It would be very helpful.

**Comment by fink-stanislav** [comment]
@dsandii the model supports returning of scores. To get them you should update `fetches` dictionary with the following key-values:
`'b_scores': predictions_dict['Backward/scores'],
'f_scores': predictions_dict['Forward/scores']`
Then, after session run, you will find `b_scores` and `f_scores` in `sess_outputs`. See `demo.py`, all mentioned variables (`fetches`, etc.) are defined there.

**Comment by AyushP123** [comment]
https://github.com/bgshih/aster/issues/22#issuecomment-533908736

**Comment by Shivanshmundra** [comment]
@fink-stanislav Since TF 1.* is depreciated and this repository has a support for TF2.0, Can you tell how to get confidence score for tf 2.0 model from [here](https://github.com/bgshih/aster/tree/master/tf2_utils)? 
Thanks!
