### ISSUE TITLE
中文定长训练，不定长识别？

### ISSUE THREAD

**Issue by Hubert2102** [bgshih/aster#40]
你好，我用虚拟生成的10个字的数据进行训练，https://pan.baidu.com/s/1dFda6R3#list/path=%2F ，训练之后，在预测的时候结果也总是10个字左右，少于10个字的图片，预测就有重复字，多于10个字的图片，预测就会丢字，总之最后的结果都会是10±2个字，请问这是什么情况啊，不是应该支持不定长的识别么

**Comment by ChChwang** [comment]
所有的都是10个字符吗，训练集里如果有少于10个的呢

**Comment by NK-Hubert** [comment]
> 
> 
> 所有的都是10个字符吗，训练集里如果有少于10个的呢

不知道，我的训练集全都是10个字，没有少于10个字的，不过CRNN就是这么训练的，是支持不定长识别的，这个还没搞清楚

**Comment by li675599061** [comment]
@Hubert2102  兄台能否分享一下训练中文字符的详细步骤

**Comment by Serenade-J** [comment]
@li675599061 我也在训练中文字符，要不要加微信聊一下。。13126710122，现在模型还没训通想跟你交流一下

**Comment by Serenade-J** [comment]
@li675599061 我们对一下改动的地方

**Comment by pageedward** [comment]
@li675599061 @Serenade-J 请问中文训练你跑通了吗，训练数据里面的keypoints是必须的嘛，之前用crnn-pytorch版label大概是这样的，
![image](https://user-images.githubusercontent.com/26244036/56780042-4d783600-6810-11e9-9193-47e6bc34e7c1.png)

**Comment by Ourano** [comment]
> 你好，我用虚拟生成的10个字的数据进行训练，https://pan.baidu.com/s/1dFda6R3#list/path=%2F ，训练之后，在预测的时候结果也总是10个字左右，少于10个字的图片，预测就有重复字，多于10个字的图片，预测就会丢字，总之最后的结果都会是10±2个字，请问这是什么情况啊，不是应该支持不定长的识别么

您好，这个问题解决了吗。我按照Issues#36的中文训练进行了修改，最终在测试的时候也是碰到了这种识别输出都是10个字符定长的问题（无论输入大于还是小于10个字符）。请问您找到是什么原因了吗

**Comment by Hubert2102** [comment]
> 
> 
> > 你好，我用虚拟生成的10个字的数据进行训练，https://pan.baidu.com/s/1dFda6R3#list/path=%2F ，训练之后，在预测的时候结果也总是10个字左右，少于10个字的图片，预测就有重复字，多于10个字的图片，预测就会丢字，总之最后的结果都会是10±2个字，请问这是什么情况啊，不是应该支持不定长的识别么
> 
> 您好，这个问题解决了吗。我按照Issues#36的中文训练进行了修改，最终在测试的时候也是碰到了这种识别输出都是10个字符定长的问题（无论输入大于还是小于10个字符）。请问您找到是什么原因了吗

你好，我的经验是用不定长数据对ASTER进行训练，不过在我的数据中，ASTER的中文识别能力目前不如CRNN
