### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by zhuliqian** [bgshih/aster#6]
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status
CMakeFiles/aster.dir/build.make:146: recipe for target 'libaster.so' failed
make[2]: *** [libaster.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/aster.dir/all' failed
make[1]: *** [CMakeFiles/aster.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by chumengdd** [comment]
Did you fix it？I met same error.

**Comment by 1037861070** [comment]
Is there any solution?

**Comment by XiaoYigwr** [comment]
Did you fix it？I met same error.

**Comment by zealian** [comment]
If you use python2, try to fix 'python3' commands to 'python' in ''c_ops/CMakeLists.txt". 

This works for my case.

**Comment by ZDDEAN** [comment]
我也遇到相同的问题，请问有解决的？

**Comment by RaidasGrisk** [comment]
The below fix worked for me:
https://github.com/bgshih/aster/issues/56#issuecomment-501973315
