### ISSUE TITLE
run the demo error

### ISSUE THREAD

**Issue by yilanwanglu** [bgshih/aster#62]
when l ran the demo, it occured such error:ImportError: cannot import name 'pipeline_pb2'.

**Comment by parksunwoo** [comment]
i have same error and i solved it !!
in terminal  
[/path/to/aster]# export PYTHONPATH='.'
[/path/to/aster]# cd ..
[/path/to]# python3 aster/demo.py

**Comment by yilanwanglu** [comment]
thank you!
i executed the Installation again, then it could work.
