### ISSUE TITLE
那个PYTHONPATH怎么添加呀

### ISSUE THREAD

**Issue by hhf443** [bgshih/aster#71]
一直找不到aster模块，把import后的aster.全删完之后，又提示没有aster/experiments/demo/config/trainval.prototxt文件，可实际是存在的。路径一直搞不对

**Comment by KaLuLas** [comment]
aster/experiments/demo/config/trainval.prototxt是相对地址，在aster目录的上一级目录执行命令就能找到prototxt文件了，临时添加PYTHONPATH用 export PYTHONPATH = $PYTHONPATH: 这里写aster目录所在的绝对地址

**Comment by 1037861070** [comment]
> 一直找不到aster模块，把import后的aster.全删完之后，又提示没有aster/experiments/demo/config/trainval.
我也是这个问题，楼主解决了吗？

**Comment by DanLiu0623** [comment]
@hhf443 @1037861070 添加路径的时候，作者说的Add /path/to/aster to PYTHONPATH, or set this variable for every run会报ModuleNotFoundError: No module named 'aster'这个错误。添加到aster的上一层路径就可以了，比如我的目录是/data0/aster。我在添加的时候就是export PYTHONPATH=/data0，就可以了。
