### ISSUE TITLE
No op named StringReverse in defined operations. (while importing the graph_def from .pb file)

### ISSUE THREAD

**Issue by rfdeng** [bgshih/aster#72]
I have generated the pb file from the model.ckpt. When i am going to load the pb file to predict, I encountered this problem:

Traceback (most recent call last):
  File "pb_demo.py", line 18, in <module>
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
    raise ValueError('No op named %s in defined operations.' % node.op)
ValueError: No op named StringReverse in defined operations.
 
I think the reason maybe the op StringReverse which seems written by the author in directory aster/c_op is not included in the tf1.4.

Does anyone know how to solve this problem? Thanks in advance.

**Comment by dsandii** [comment]
You have to load the compiled custom operations found in `/aster/c_ops/libaster.so`. This can be done lazily by importing the following module into the module where you're using your `.pb`.

`from aster.c_ops import ops`

You don't need to actually use it, only import it.
