### ISSUE TITLE
Are learning rate and num_steps too large?

### ISSUE THREAD

**Issue by FoxerLee** [bgshih/aster#8]
Sorry to bother you... In your trainval.prototxt, I noticed that the Initial learning rate is 1, and it will drop with the training progress. But during my training, the acc is keeping about 0.15 and not growing during the 0-600000 step. Is it because of the high learning rate?
And the num_steps is 1200000, so it will spend about 1 week for training... So It`s difficult for me to adjust parameters... Is there any possibility that I can quickly verify whether my network can eventually be trained well?

Dataset: 
 - http://cvit.iiit.ac.in/projects/SceneTextUnderstanding/IIIT5K.html
 - It contains 5000 cropped word images from Scene Texts and born-digital images.

Computer: 
 - GPU: Tesla-V100-PCIE-16GB

Thanks a lot~

**Comment by bgshih** [comment]
@FoxerLee ADADELTA uses larger base learning rate and lr=1 is its default. The training takes ~2 days on a GTX Titan Xp so on a Tesla-V100 it should take shorter.

**Comment by jjccyy** [comment]
@FoxerLee  hi ,When I run create_iiit5k_tfrecord.py，I got an error
Traceback (most recent call last):
  File "aster/tools/create_iiit5k_tfrecord.py", line 60, in <module>
    create_iiit5k_subset('/home/q/aster/tools/data/iiit5k_train.tfrecord', train_subset=True)
  File "aster/tools/create_iiit5k_tfrecord.py", line 52, in create_iiit5k_subset
    dataset_util.bytes_feature(('\t'.join(lexicon)).encode('utf-8'))
UnboundLocalError: local variable 'lexicon' referenced before assignment
When I delete 52 lines, it has work.During my training, the acc is keeping about 0.15，How do you solve this problem?
Thanks

**Comment by colorful101** [comment]
hello,i'm sorry to bother you.
the model trained on icdar2015 traininig dataset，however，when the accuracy in training data=100%,the accuracy  in test set is always about 20%(the testing data is ic15 testing dataset)...could you please tell me the reason and where the problem exits?Thanks a lot~ @bgshih
