### ISSUE TITLE
Train only the text recognition part

### ISSUE THREAD

**Issue by AyushP123** [bgshih/aster#89]
Hi,

I want to train aster for recognizing text in an image. All the images contain just a line of text. Can I just train the recognition part, without training the localization or the rectification network?. What changes do I need to make to the prototxt file for this? 

As far as I understand I should use the "create_ic15_tfrecord.py" script present in tools for my tasks. The other scripts which do not contain bbox ( as I do not want to annotate the bounding boxes for each text ) contain the term "lexicons". Could you explain what that term is?

**Comment by Cabbagehust2507** [comment]
@AyushP123  How did you do that? Can y ou show me? Thank you so much
