### ISSUE TITLE
convert Aster to tensorflow serving?

### ISSUE THREAD

**Issue by lynx97** [bgshih/aster#98]
Has anyone tried to do convert aster model to tensorflow serving?

**Comment by xxxpsyduck** [comment]
@lynx97 I tried but couldn't make it. He uses pyfunc which is incompatible with tf serving

**Comment by lynx97** [comment]
> @lynx97 I tried but couldn't make it. He uses pyfunc which is incompatible with tf serving
I converted to tfserving but when loading serving model, It have to build StringReverse ops.
